Begin v-1.0 work
This commit is the start of the new design for v-1.0. The idea
is to move all configuration data into zfs properties, making
the zfshadow script a simple front end for manipulating those
properties, as well as for sending datasets based on said properties.

diff --git a/zfshadow b/zfshadow
--- a/zfshadow
+++ b/zfshadow
@@ -8,36 +8,34 @@ PATH=/bin:/usr/bin:/sbin
 
 version="0.1"
 
-host=""
-port="22"
-self="`basename $0`"
-dotpid="/var/run/$self.pid"
 base_snap="shadow.base"
 delta_snap="shadow.delta"
 ec=0
 
-process_dataset()
+unset zfshadow_tags
+
+send_dataset()
 {
-    local local=`echo "$1" | sed 's/:.*//'`
-    local remote=`echo "$1" | sed 's/.*://'`
+    local local=$(echo "$1" | sed 's/:.*//')
+    local remote=$(echo "$1" | sed 's/.*://')
 
     zfs list -H "$local" >/dev/null 2>&1
 
     if [ $? != 0 ]
     then
-        fail "could not find dataset $local"
+        err "could not find dataset $local"
         return
     fi
 
     # get a list of all the datasets under the specified dataset
-    local datasets=`zfs list -H -r -o name $local`
+    local datasets=$(zfs list -H -r -o name $local)
 
     # iterate through each dataset and send a backup
     for dataset in $datasets
     do
-        log "  started processing $dataset at `date`"
+        log "  started processing $dataset at $(date)"
 
-        local ignore=`zfs get -H -o value zfshadow:ignore $dataset`
+        local ignore=$(zfs get -H -o value zfshadow:ignore $dataset)
 
         if [ "$ignore" == "yes" ]
         then
@@ -46,7 +44,7 @@ process_dataset()
         fi
 
         # calculate what the remote dataset's name is
-        local remote_dataset="$remote`echo $dataset | sed 's|^[^/]*||'`"
+        local remote_dataset="$remote$(echo $dataset | sed 's|^[^/]*||')"
 
         # blindly try to create the base snapshot, then check the
         # return code to branch on either sending the initial data, or sending
@@ -71,13 +69,13 @@ process_dataset()
 
             log "    sending $dataset@$base_snap to $host"
 
-            local send_output=`zfs send $dataset@$base_snap | gzip | ssh $host -p $port "gzcat | zfs recv -duv $remote" 2>&1`
+            local send_output=$(zfs send $dataset@$base_snap | gzip | ssh $host -p $port "gzcat | zfs recv -duv $remote" 2>&1)
 
             if [ $? == 0 ]
             then
                 log "    successfully sent snapshot '$dataset@$base_snap'"
             else
-                fail "    failed to send snapshot '$dataset@$base_snap', destroying newly created base snapshot - output: $send_output"
+                err "    failed to send snapshot '$dataset@$base_snap', destroying newly created base snapshot - output: $send_output"
 
                 # destroy the newly created base snapshot so that the next time
                 # this script is run, the base snapshot will be re-created and
@@ -109,14 +107,14 @@ process_dataset()
                 fi
             done
 
-            local snapshot_output=`zfs snapshot $dataset@$delta_snap 2>&1`
+            local snapshot_output=$(zfs snapshot $dataset@$delta_snap 2>&1)
 
             if [ $? != 0 ]
             then
                 # despite trying to clean up any left over snapshots, we still
                 # failed to create a snapshot. go ahead and abort for now, with the
                 # hope that a later invocation of this script will have success
-                fail "  failed to create the delta snapshot '$dataset@$delta_snap' - output: $snapshot_output"
+                err "  failed to create the delta snapshot '$dataset@$delta_snap' - output: $snapshot_output"
 
                 # move on to the next dataset
                 continue
@@ -124,7 +122,7 @@ process_dataset()
 
             log "    sending $dataset@$delta_snap to $host"
 
-            local send_output=`zfs send -i $base_snap $dataset@$delta_snap | gzip | ssh $host -p $port "gzcat | zfs recv -duv $remote" 2>&1`
+            local send_output=$(zfs send -i $base_snap $dataset@$delta_snap | gzip | ssh $host -p $port "gzcat | zfs recv -duv $remote" 2>&1)
 
             if [ $? == 0 ]
             then
@@ -132,7 +130,7 @@ process_dataset()
 
                 update_snapshots $dataset $remote_dataset
             else
-                fail "    failed to send $dataset@$delta_snap, destroying newly created delta snapshot - output: $send_output"
+                err "    failed to send $dataset@$delta_snap, destroying newly created delta snapshot - output: $send_output"
 
                 # since we couldn't send it, just destroy it. If this
                 # script gets invoked again the delta snapshot will just be recreated.
@@ -140,8 +138,75 @@ process_dataset()
             fi
         fi
 
-        log "  finished processing $dataset at `date`"
+        log "  finished processing $dataset at $(date)"
     done
+}
+
+send_tag()
+{
+    local tag="$1"
+
+    echo "sending [$tag]"
+}
+
+load_tags()
+{
+    if [ -z "$zfshadow_tags" ]
+    then
+        zfshadow_tags=$(zfs get -H -s local -t filesystem -o property all | grep '^zfshadow:[a-zA-Z0-9_]*\.cfg$' | sed -e 's/^zfshadow:\([a-zA-Z0-9_]*\)\.cfg$/\1/' | sort | uniq)
+    fi
+}
+
+check_tag()
+{
+    local check_tag="$1"
+
+    load_tags
+
+    for tag in $zfshadow_tags
+    do
+        if [ $check_tag == $tag ]
+        then
+            return 0
+        fi
+    done
+
+    return 1
+}
+
+get_datasets_for_tag()
+{
+    local tag="$1"
+
+    zfs get -H -t filesystem -o name,value zfshadow:$tag | grep '[[:space:]]send' | awk '{ print $1 }'
+}
+
+parse_tags()
+{
+    load_tags
+
+    local tags=""
+
+    if [ $# == 0 ]
+    then
+        tags=$zfshadow_tags
+    else
+        while [ $# -gt 0 ]
+        do
+            check_tag "$1" || exerr "tag $1 does not exist"
+
+            if [ -z $tags ]
+            then
+                tags="$1"
+            else
+                tags=$(echo "$tags $1")
+            fi
+
+            shift
+        done
+    fi
+
+    echo $tags
 }
 
 update_snapshots()
@@ -151,7 +216,7 @@ update_snapshots()
     ssh $host -p $port zfs destroy $2@$base_snap >/dev/null 2>&1
 
     log "      renaming remote snapshot $2@$delta_snap to $2@$base_snap"
-    local rename_output=`ssh $host -p $port zfs rename $2@$delta_snap $2@$base_snap 2>&1`
+    local rename_output=$(ssh $host -p $port zfs rename $2@$delta_snap $2@$base_snap 2>&1)
 
     if [ $? == 0 ]
     then
@@ -162,25 +227,31 @@ update_snapshots()
         log "      renaming local snapshot $1@$delta_snap to $1@$base_snap"
         zfs rename $1@$delta_snap $1@$base_snap >/dev/null 2>&1
     else
-        fail "      failed to rename the remote snapshot $2@$delta_snap to $2@$base_snap - output: $rename_output"
+        err "      failed to rename the remote snapshot $2@$delta_snap to $2@$base_snap - output: $rename_output"
     fi
 }
 
 log()
 {
     echo "$1"
-    logger -t $self "$1"
+    logger -t zfshadow "$1"
 }
 
-fail()
+err()
 {
     ec=1
-    log "FAILURE: $1"
+    log "_FAILURE_: $1"
+}
+
+exerr()
+{
+    echo -e "$*" >&2
+    exit 1
 }
 
 usage()
 {
-    echo "usage: $self [-p port] [-h] dest_host local_dataset1:remote_dataset1 [local_dataset2:remote_dataset2] ..."
+    echo "usage: zfshadow [-p port] [-h] dest_host local_dataset1:remote_dataset1 [local_dataset2:remote_dataset2] ..."
     echo " -p port: the ssh port to connect to on the remote host"
     echo " -h: print this help"
     echo " -v: print the version info"
@@ -194,68 +265,98 @@ version()
     echo "zfshadow version $version"
 }
 
-if [ ! `whoami` = "root" ]
-then
-    echo "$self must be run as root"
-    exit 1
-fi
+########## END FUNCTION DECLARATIONS ##########
 
-while getopts ":p:hv" opt
-do
-    case $opt in
-        p)
-            port=$OPTARG
-            ;;
-        h)
-            usage
-            exit 0
-            ;;
-        v)
-            version
-            exit 0
-            ;;
-        \?)
-            usage
-            exit 1
-            ;;
-        :)
-            echo "-$OPTARG requires a value"
-            usage
-            exit 1
-            ;;
-    esac
-
-    shift $(($OPTIND-1))
-done
-
-if [ $# -lt 2 ]
-then
-    usage
-    exit 1
-fi
-
-host=$1
-shift
-
-pid=`pgrep -F $dotpid 2>/dev/null`
-
-if [ ! -z $pid ]
-then
-    log "$self is already running as pid $pid, exiting"
-    exit 0
-fi
-
-echo $$ > $dotpid
-
-log "started processing datasets at `date`"
-
-while [ $# -gt 0 ]
-do
-    process_dataset "$1"
+case "$1" in
+#
+# create - create a tag and its properties
+#
+create)
     shift
-done
 
-log "finished processing datasets at `date`"
-log ""
+    if [ $# -lt 3 ]
+    then
+        usage
+        exit 1
+    fi
+
+    echo "$1" | grep -qv "[^a-zA-Z0-9_]" || \
+        exerr "tag names can only contain a-z, 0-9, and _ characters"
+
+    tag="$1"
+
+    shift; while getopts :t:h: arg; do case ${arg} in 
+      t) tag_target=${OPTARG};; 
+      h) tag_host=${OPTARG};;
+      ?) usage;; 
+    esac; done; shift $(( ${OPTIND} - 1 ))
+
+    [ ! -z $tag_target ] || \
+        exerr "the target name is required (-t <target>)"
+
+    # when creating a new tag, add the tag properties to every pool
+    # so it's a global property regardless of what pools are connected
+    all_pools=$(zpool list -H -o name)
+
+    zfs set zfshadow:$tag.cfg=$tag_host $all_pools
+
+    ;;
+
+#
+# tag - tag a dataset for sending
+#
+tag)
+    ;;
+
+#
+# list - list all tags
+#
+list)
+    shift
+
+    list_tags=$(parse_tags $@)
+
+    [ $? == 0 ] || exit 1
+
+    printf "TAG\t\tDATASET\n"
+
+    for tag in $list_tags
+    do
+        datasets=$(get_datasets_for_tag $tag)
+
+        for dataset in $datasets
+        do
+            printf "%s\t\t%s\n" $tag $dataset
+        done
+    done
+    ;;
+#
+# send - send datasets somewhere
+#
+send)
+    shift
+
+    send_tags=$(parse_tags $@)
+
+    [ $? == 0 ] || exit 1
+
+    log "started processing datasets at $(date)"
+
+    for tag in $send_tags
+    do
+        send_tag $tag
+    done
+    
+    log "finished processing datasets at $(date)"
+    ;;
+
+#
+# error - unrecognized command
+#
+*)
+    usage
+    ;;
+esac
+
 
 exit $ec
